apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: demo-app
  namespace: default
spec: 
  rules: 
    - host: 377c0f17-854e-4a1b-863d-a1b685ae2ef7.lb.civo.com
      http: 
        paths: 
          - backend: 
              service: 
                name: demo-app 
                port: 
                  number: 8080 
            path: / 
            pathType: Prefix 
