apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: podinfo 
spec: 
  ingressClassName: nginx 
  rules: 
    - host: 377c0f17-854e-4a1b-863d-a1b685ae2ef7.lb.civo.com
      http: 
        paths: 
          - backend: 
              service: 
                name: podinfo 
                port: 
                  number: 8080 
            path: / 
            pathType: Prefix 
