apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

