# apiVersion: v1 
# kind: Service 
# metadata: 
#   name: podinfo 
# spec: 
#   ports: 
#     - port: 80 
#       targetPort: 9898 
#       nodePort: 30001
#       name: base
#     - port: 81 
#       targetPort: 9797 
#       name: metric
#   selector: 
#     app: podinfo 
#   type: LoadBalancer 
apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - port: 9797
      targetPort: http-metrics
      protocol: TCP
      name: grpc
