apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: (PRODUCT)-(BRANCH)
  namespace: default
spec:
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 99
        type: Utilization
    type: Resource
  minReplicas: 0
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: (PRODUCT)-(BRANCH)
