name: Pull-request Created
on:
  pull_request:
    types: [closed]


permissions:
  actions: write
  contents: read
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: 🐳 CLosed
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          repository: magudb/fleet-infra
          path: fleet-infra
      - name: remove Kubernetes deployment
        run: |
          rm -rf fleet-infra/clusters/kube-local/features/demo-app-${GIT_BRANCH_NAME,,}
          rm -f fleet-infra/clusters/kube-local/features/demo-app-${GIT_BRANCH_NAME,,}-source.yaml
          rm -f fleet-infra/clusters/kube-local/features/demo-app-${GIT_BRANCH_NAME,,}-kustomization.yaml
      - name: Pushes to fleet-infra
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: 'fleet-infra'
          destination-github-username: 'magudb'
          destination-repository-name: 'fleet-infra'
          user-email: mau@cbit.dk
          target-branch: main
      

 