name: 🚀 RELEASE 
on:
  push:
    tags:
        - "v*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: 🐳 Build  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Version
        id: image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "VERSION=${{ steps.image.outputs.version }}"
            "SHA=${{ steps.commit.outputs.short }}"
  release:
    name: 🐳 Build  
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get Version
        id: image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      - name: Update Image Version in deployment.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "ghcr.io/magudb/demo-app:${{ steps.image.outputs.version }}"' 'deployment/deployment.yaml'
      - uses: EndBug/add-and-commit@v9
        with:
          new_branch: main
          #github_token: ${{ secrets.GH_TOKEN }}
          add: './deployment/deployment.yaml'          
          message: '[RELEASE] Version updated'


